# Config file for github.com/alpkeskin/mosint
# For default usage just rename this file to .mosint.yaml and put it in your home directory

services:
  breach_directory_api_key: "0a48f94a09msh1f754d78440b38ap1dfcc5jsnc3c168aeb561"
  #emailrep_api_key: SET_YOUR_API_KEY_HERE
  #hunter_api_key: "e5f09ada9e10c0498463ed7d8bc8b9fd333f3a5d"
  #intelx_api_key:     9ccbff29-d18b-4754-800b-3bd93c45aaff
  #haveibeenpwned_api_key: SET_YOUR_API_KEY_HERE

settings:
  #intelx_max_results: 50
