# Config file for github.com/alpkeskin/mosint
# For default usage just rename this file to .mosint.yaml and put it in your home directory

services:
  #breach_directory_api_key: ""
  #emailrep_api_key: SET_YOUR_API_KEY_HERE
  #hunter_api_key: ""
  #intelx_api_key:
  #haveibeenpwned_api_key: SET_YOUR_API_KEY_HERE

settings:
  #intelx_max_results: 50
